// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/2/auth_system_2.1":{"path":"2/auth_system_2/1","id":"docs/2/auth_system_2.1","parentId":"DocLayout"},"docs/2/auth_system_2.2":{"path":"2/auth_system_2/2","id":"docs/2/auth_system_2.2","parentId":"DocLayout"},"docs/2/auth_system_2.3":{"path":"2/auth_system_2/3","id":"docs/2/auth_system_2.3","parentId":"DocLayout"},"docs/2/auth_system_2.4":{"path":"2/auth_system_2/4","id":"docs/2/auth_system_2.4","parentId":"DocLayout"},"docs/2/auth_system_2.5":{"path":"2/auth_system_2/5","id":"docs/2/auth_system_2.5","parentId":"DocLayout"},"docs/2/auth_system_2.6":{"path":"2/auth_system_2/6","id":"docs/2/auth_system_2.6","parentId":"DocLayout"},"docs/2/auth_system_2.7":{"path":"2/auth_system_2/7","id":"docs/2/auth_system_2.7","parentId":"DocLayout"},"docs/3/auth_system_3.1":{"path":"3/auth_system_3/1","id":"docs/3/auth_system_3.1","parentId":"DocLayout"},"docs/3/auth_system_3.2":{"path":"3/auth_system_3/2","id":"docs/3/auth_system_3.2","parentId":"DocLayout"},"docs/3/auth_system_3.3":{"path":"3/auth_system_3/3","id":"docs/3/auth_system_3.3","parentId":"DocLayout"},"docs/1/auth_system_1":{"path":"1/auth_system_1","id":"docs/1/auth_system_1","parentId":"DocLayout"},"docs/4/auth_system_4":{"path":"4/auth_system_4","id":"docs/4/auth_system_4","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/zhm/0-core/400-前端/front/auth-system/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.0_@swc+helpers@0.5.1_@types+node@22.13.13_@types+react@18.3.18_e_vy6ghkxpr6t6op4s6yiyovxwry/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/zhm/0-core/400-前端/front/auth-system/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/zhm/0-core/400-前端/front/auth-system/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.0_@swc+helpers@0.5.1_@types+node@22.13.13_@types+react@18.3.18_e_vy6ghkxpr6t6op4s6yiyovxwry/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/2/auth_system_2.1': React.lazy(() => import(/* webpackChunkName: "docs__2__auth_system_2.1.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.1.md')),
'docs/2/auth_system_2.2': React.lazy(() => import(/* webpackChunkName: "docs__2__auth_system_2.2.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.2.md')),
'docs/2/auth_system_2.3': React.lazy(() => import(/* webpackChunkName: "docs__2__auth_system_2.3.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.3.md')),
'docs/2/auth_system_2.4': React.lazy(() => import(/* webpackChunkName: "docs__2__auth_system_2.4.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.4.md')),
'docs/2/auth_system_2.5': React.lazy(() => import(/* webpackChunkName: "docs__2__auth_system_2.5.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.5.md')),
'docs/2/auth_system_2.6': React.lazy(() => import(/* webpackChunkName: "docs__2__auth_system_2.6.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.6.md')),
'docs/2/auth_system_2.7': React.lazy(() => import(/* webpackChunkName: "docs__2__auth_system_2.7.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.7.md')),
'docs/3/auth_system_3.1': React.lazy(() => import(/* webpackChunkName: "docs__3__auth_system_3.1.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.1.md')),
'docs/3/auth_system_3.2': React.lazy(() => import(/* webpackChunkName: "docs__3__auth_system_3.2.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.2.md')),
'docs/3/auth_system_3.3': React.lazy(() => import(/* webpackChunkName: "docs__3__auth_system_3.3.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.3.md')),
'docs/1/auth_system_1': React.lazy(() => import(/* webpackChunkName: "docs__1__auth_system_1.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/1/auth_system_1.md')),
'docs/4/auth_system_4': React.lazy(() => import(/* webpackChunkName: "docs__4__auth_system_4.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/4/auth_system_4.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/zhm/0-core/400-前端/front/auth-system/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.0_@swc+helpers@0.5.1_@types+node@22.13.13_@types+react@18.3.18_e_vy6ghkxpr6t6op4s6yiyovxwry/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
