// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhm/0-core/400-前端/front/auth-system/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.0_@swc+helpers@0.5.1_@types+node@22.13.13_@types+react@18.3.18_e_vy6ghkxpr6t6op4s6yiyovxwry/node_modules/dumi/theme-default/slots/ColorSwitch/index.js';
