// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.1.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.1.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.2.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.2.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.3.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.3.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.4.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.4.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.5.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.5.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.6.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.6.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.7.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.7.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.1.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.1.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.2.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.2.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.3.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.3.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/1/auth_system_1.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/1/auth_system_1.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/4/auth_system_4.md?type=frontmatter';
import { demoIndex as dmi11 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/4/auth_system_4.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/index.md?type=frontmatter';
import { demoIndex as dmi12 } from '/Users/zhm/0-core/400-前端/front/auth-system/docs/index.md?type=demo-index';

export const filesMeta = {
  'docs/2/auth_system_2.1': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.1.md?type=text'),
  },
  'docs/2/auth_system_2.2': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.2.md?type=text'),
  },
  'docs/2/auth_system_2.3': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.3.md?type=text'),
  },
  'docs/2/auth_system_2.4': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.4.md?type=text'),
  },
  'docs/2/auth_system_2.5': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.5.md?type=text'),
  },
  'docs/2/auth_system_2.6': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.6.md?type=text'),
  },
  'docs/2/auth_system_2.7': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/2/auth_system_2.7.md?type=text'),
  },
  'docs/3/auth_system_3.1': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.1.md?type=text'),
  },
  'docs/3/auth_system_3.2': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.2.md?type=text'),
  },
  'docs/3/auth_system_3.3': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/3/auth_system_3.3.md?type=text'),
  },
  'docs/1/auth_system_1': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/1/auth_system_1.md?type=text'),
  },
  'docs/4/auth_system_4': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/4/auth_system_4.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/zhm/0-core/400-前端/front/auth-system/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
